# Use root/example as user/password credentials
version: '3.1'

networks:
  app-tier:
    driver: bridge

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: lv
      MYSQL_USER: lv
      MYSQL_PASSWORD: lv
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-tier

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier

  web:
    build: .
    command: ["./run_web.sh"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    networks:
      - app-tier


