version: '3.1'
services:
  web:
    build: .
    command: ["./run_web.sh"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=lv_web
      - MYSQL_ROOT_PASSWORD=lv_web_password

  redis:
    image: redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes




