version: '3.1'
services:
  web:
    build: .
    command: ["./run_web.sh"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    volumes:
#      - docker_configs/mysql/my.cnf:/etc/my.cnf
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=lv_web
      - MYSQL_ROOT_PASSWORD=lv_web_password

  redis:
    image: redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes




