version: '3'
services:
  web:
    build: .
    command: ["./run_web.sh"]
#    command:  uwsgi --ini uwsgi_deploy.ini
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    volumes:
#      - docker_configs/mysql/my.cnf:/etc/my.cnf
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=lv_web
      - MYSQL_ROOT_PASSWORD=lv_web_password

  redis:
    image: redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  celery:
    build: .
    command: celery -A LV worker -l info -f log/celery.log
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A LV beat -l info -f log/celery_beat.log
    volumes:
      - .:/code
    depends_on:
      - db
      - redis




